### ISSUE TITLE
install gemmR

### ISSUE THREAD

**Issue by ErikSeng** [jchrszcz/gemmR#8]
Hi,
while installing gemmR I get the following error message.

"invalid conversion from 'long long unsigned int' to 'SEXP' [-fpermissive]
  SEXP x = object"
This message is comming from "Rcpp/internal/wrap.h" and referes to "make: *** [kt_gemmR.o] Error 1".

I use R Version 3.4.0 and RTools 3.4.0.1964 on a Windows machine and so I need to compile your package.

Do you know how I can prevent this error? 
Thank you for your support.
Erik

**Comment by jchrszcz** [comment]
Erik,

I don't have easy access to a windows machine for a few days, but I can verify that this package installs under the current versions of R (3.4.3) and Rcpp (0.14.12) on Mac OS and Linux. 

I can check this after the new year, but would you mind including your sessionInfo() output as well? I might also go a bit faster with the full install text, not just the error.

Thanks,
Jeff

**Comment by jchrszcz** [comment]
Ok, summary: the problem was that Windows didn't know what to do with size_t vars under the compiler options CRAN requires to compile. I've abandoned the idea of CRAN for this package, so I've altered the DESCRIPTION file to force C++11 for compilation, which solve the issue for me under R 3.4.2 and Rcpp 0.12.14. I'm hoping this works back to R 3.4.0 (I know of no reason it wouldn't).

**Comment by ErikSeng** [comment]
Hi Jeff, 
this is my first day at work this year and you made my day. 
Thanks a lot

Erik
